<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Bajaj</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>883351ec-849e-40b3-a7eb-2fa9ce71c09f</testSuiteGuid>
   <testCaseLink>
      <guid>eb37bc97-debb-49c1-b488-689a18b98540</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test1By Chirag</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed97ebb0-b61c-4416-889e-22fa9dbc7622</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9218dc51-db95-43d6-ba01-abc1de4fea16</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c5021f8-93a2-4e93-a6a1-62c66d0760b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dc4a352-752a-4dea-9b6b-d9aaa2af120a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d61dd6ef-6a3e-4b91-bde2-e6e3d8172284</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42f9676f-dc39-4af2-98bf-103266d42c32</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
