<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CIBIL_StatusMatch</name>
   <tag></tag>
   <elementGuidId>998c9e3a-8e8e-4762-b1d1-bc46cd2472d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@aria-labelledby][contains(@class,'visible')]//li/a[@title='Match'])[last()]   
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
