<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OpportunityName</name>
   <tag></tag>
   <elementGuidId>9c70e3ab-7c5d-4d8b-a31d-9e24d2c78e79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//table//td)[1]//a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
